package com.leaveflow;
import java.math.*; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class LeaveController {
 private final JdbcTemplate db; private final BalanceCalculator balances=new BalanceCalculator(); public LeaveController(JdbcTemplate db){this.db=db;}
 @GetMapping("/health") Map<String,String> health(){return Map.of("status","UP","service","LeaveFlow API");}
 @GetMapping("/state-machine") Map<String,Object> stateMachine(){Map<String,Object> r=new LinkedHashMap<>(); for(var s:Workflow.State.values())r.put(s.name(),Workflow.allowed(s).stream().map(Enum::name).toList()); return r;}
 @GetMapping("/leave/balance") Map<String,Object> balance(@RequestParam(defaultValue="employee@example.com")String email){var row=db.queryForMap("select joined_on from employees where email=?",email); BigDecimal entitlement=balances.entitlement(((java.sql.Date)row.get("joined_on")).toLocalDate(),2026,new BigDecimal("20")); BigDecimal used=db.queryForObject("select coalesce(sum(days),0) from leave_requests r join employees e on e.id=r.employee_id where e.email=? and r.state='APPROVED'",BigDecimal.class,email); BigDecimal pending=db.queryForObject("select coalesce(sum(days),0) from leave_requests r join employees e on e.id=r.employee_id where e.email=? and r.state in ('MANAGER_PENDING','MANAGER_ESCALATED','HR_PENDING','HR_ESCALATED')",BigDecimal.class,email); return Map.of("annualEntitlement",entitlement,"approvedUsed",used,"pending",pending,"available",entitlement.subtract(used).subtract(pending),"explanation","Eligible months are counted from the join month; weekends are excluded by this demo policy.");}
 @GetMapping("/leave/requests/{id}") Map<String,Object> request(@PathVariable long id){return db.queryForMap("select r.*,e.display_name,e.email,t.name team_name from leave_requests r join employees e on e.id=r.employee_id left join teams t on t.id=e.team_id where r.id=?",id);}
 @PostMapping("/leave/requests/{id}/events/{event}") ResponseEntity<?> transition(@PathVariable long id,@PathVariable Workflow.Event event,@RequestParam(defaultValue="manager@example.com")String actor,@RequestParam(required=false)String comment){var row=db.queryForMap("select state from leave_requests where id=?",id); Workflow.State old=Workflow.State.valueOf((String)row.get("state")); Workflow.State next; try{next=Workflow.next(old,event);}catch(IllegalArgumentException e){return ResponseEntity.badRequest().body(Map.of("code","INVALID_STATE_TRANSITION","message",e.getMessage()));} if(event.name().startsWith("MANAGER")&&!actor.equals("manager@example.com"))return ResponseEntity.status(403).body(Map.of("code","FORBIDDEN","message","Only the assigned manager may decide this stage.")); if(event.name().startsWith("HR")&&!actor.equals("hr@example.com"))return ResponseEntity.status(403).body(Map.of("code","FORBIDDEN","message","Only HR may decide this stage.")); db.update("update leave_requests set state=?, pending_since=CURRENT_TIMESTAMP where id=?",next.name(),id); db.update("insert into leave_audit_events(request_id,actor,actor_role,action,previous_state,new_state,comment) values(?,?,?,?,?,?,?)",id,actor,actor.startsWith("hr")?"HR":"MANAGER",event.name(),old.name(),next.name(),comment); return ResponseEntity.ok(Map.of("id",id,"previousState",old,"state",next,"allowedActions",Workflow.allowed(next)));}
 @GetMapping("/manager/conflicts/{id}") Map<String,Object> conflict(@PathVariable long id){var r=request(id); long team=((Number)db.queryForObject("select e.team_id from leave_requests r join employees e on e.id=r.employee_id where r.id=?",Long.class,id)).longValue(); int size=db.queryForObject("select count(*) from employees where team_id=?",Integer.class,team); int absent=db.queryForObject("select count(distinct r.employee_id) from leave_requests r join employees e on e.id=r.employee_id where e.team_id=? and r.id<>? and r.state='APPROVED' and r.start_date<=? and r.end_date>=?",Integer.class,team,id,r.get("end_date"),r.get("start_date")); BigDecimal pct=BigDecimal.valueOf((absent+1)*100.0/size).setScale(1,RoundingMode.HALF_UP); return Map.of("teamSize",size,"alreadyAbsent",absent,"requested",1,"projectedAbsencePercent",pct,"thresholdPercent",20,"risk",pct.compareTo(BigDecimal.valueOf(20))>0?"HIGH RISK":"NORMAL","automaticRejection",false);}
 @PostMapping("/demo/escalation/run") Map<String,Object> demoEscalate(){return runEscalation();}
 @Scheduled(fixedDelayString="${demo.escalation-check-interval-ms:60000}") public Map<String,Object> runEscalation(){int manager=escalate("MANAGER_PENDING","MANAGER_ESCALATED",24,"ESCALATE_MANAGER"); int hr=escalate("HR_PENDING","HR_ESCALATED",24,"ESCALATE_HR"); return Map.of("managerEscalated",manager,"hrEscalated",hr);}
 private int escalate(String from,String to,int hours,String event){var ids=db.queryForList("select id from leave_requests where state=? and pending_since<?",Long.class,from,java.sql.Timestamp.valueOf(LocalDateTime.now().minusHours(hours))); for(long id:ids){db.update("update leave_requests set state=? where id=?",to,id);db.update("insert into leave_audit_events(request_id,actor,actor_role,action,previous_state,new_state,comment) values(?,?,?,?,?,?,?)",id,"system","SYSTEM",event,from,to,"Approval SLA expired; governance is preserved.");} return ids.size();}
}
