-- Migrate the original demo schema to the leave-management model.
CREATE TYPE user_role AS ENUM ('EMPLOYEE', 'MANAGER', 'HR');
CREATE TYPE leave_status AS ENUM ('PENDING_MANAGER', 'PENDING_HR', 'APPROVED', 'REJECTED', 'ESCALATED');

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'EMPLOYEE',
    team VARCHAR(100) NOT NULL,
    manager_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    joining_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO users (id, name, email, password, role, team, manager_id, joining_date)
OVERRIDING SYSTEM VALUE
SELECT e.id, e.display_name, e.email, e.password_hash, e.role::text::user_role,
       COALESCE(t.name, 'HR'), NULL, e.joined_on
FROM employees e
LEFT JOIN teams t ON t.id = e.team_id
;

UPDATE users u
SET manager_id = manager_employee.id
FROM employees employee
JOIN teams team ON team.id = employee.team_id
JOIN employees manager_employee ON manager_employee.email = team.manager_email
WHERE u.id = employee.id;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);

CREATE TABLE leave_balances (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    leave_type VARCHAR(50) NOT NULL,
    total_days NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (total_days >= 0),
    used_days NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (used_days >= 0),
    remaining_days NUMERIC(5,2) GENERATED ALWAYS AS (total_days - used_days) STORED,
    year INTEGER NOT NULL CHECK (year >= 2000),
    CONSTRAINT unique_user_leave_year UNIQUE (user_id, leave_type, year)
);

ALTER TABLE leave_requests RENAME TO legacy_leave_requests;
ALTER TABLE leave_audit_events RENAME TO legacy_leave_audit_events;

CREATE TABLE leave_requests (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    leave_type VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days NUMERIC(5,2) NOT NULL CHECK (days > 0),
    reason TEXT,
    status leave_status NOT NULL DEFAULT 'PENDING_MANAGER',
    manager_comment TEXT,
    hr_comment TEXT,
    excessive_team_leave BOOLEAN NOT NULL DEFAULT FALSE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    manager_deadline TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT valid_leave_dates CHECK (end_date >= start_date)
);

INSERT INTO leave_requests
    (id, user_id, leave_type, start_date, end_date, days, status,
     manager_comment, hr_comment, applied_at, manager_deadline, updated_at)
OVERRIDING SYSTEM VALUE
SELECT old.id, old.employee_id, old.leave_type, old.start_date, old.end_date, old.days,
       CASE old.state
           WHEN 'MANAGER_PENDING' THEN 'PENDING_MANAGER'::leave_status
           WHEN 'MANAGER_ESCALATED' THEN 'ESCALATED'::leave_status
           WHEN 'HR_PENDING' THEN 'PENDING_HR'::leave_status
           WHEN 'HR_ESCALATED' THEN 'ESCALATED'::leave_status
           WHEN 'APPROVED' THEN 'APPROVED'::leave_status
           WHEN 'MANAGER_REJECTED' THEN 'REJECTED'::leave_status
           WHEN 'HR_REJECTED' THEN 'REJECTED'::leave_status
           ELSE 'PENDING_MANAGER'::leave_status
       END,
       old.manager_comment, old.hr_comment, old.created_at,
       CASE WHEN old.state IN ('MANAGER_PENDING', 'MANAGER_ESCALATED')
            THEN old.pending_since + INTERVAL '24 hours' END,
       old.created_at
FROM legacy_leave_requests old;

SELECT setval(pg_get_serial_sequence('leave_requests', 'id'), COALESCE((SELECT MAX(id) FROM leave_requests), 1), true);

CREATE TABLE leave_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES leave_requests(id) ON DELETE CASCADE,
    actor VARCHAR(120) NOT NULL,
    actor_role VARCHAR(30) NOT NULL,
    action VARCHAR(40) NOT NULL,
    previous_state VARCHAR(40),
    new_state VARCHAR(40) NOT NULL,
    comment VARCHAR(500),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO leave_audit_events
    (id, request_id, actor, actor_role, action, previous_state, new_state, comment, occurred_at)
SELECT id, request_id, actor, actor_role, action, previous_state, new_state, comment, occurred_at
FROM legacy_leave_audit_events;
SELECT setval(pg_get_serial_sequence('leave_audit_events', 'id'),
              COALESCE((SELECT MAX(id) FROM leave_audit_events), 1), true);

CREATE TABLE team_leave_rules (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    team VARCHAR(100) NOT NULL UNIQUE,
    max_percentage NUMERIC(5,2) NOT NULL DEFAULT 30.00
        CHECK (max_percentage > 0 AND max_percentage <= 100)
);
INSERT INTO team_leave_rules (team, max_percentage)
SELECT name, 20.00 FROM teams;

CREATE INDEX idx_users_team ON users(team);
CREATE INDEX idx_users_manager ON users(manager_id);
CREATE INDEX idx_leave_requests_user ON leave_requests(user_id);
CREATE INDEX idx_leave_requests_status ON leave_requests(status);
CREATE INDEX idx_leave_requests_dates ON leave_requests(start_date, end_date);
CREATE INDEX idx_leave_balances_user ON leave_balances(user_id);

-- Keep the original demo data, and add the sample users and requests from the new schema.
INSERT INTO users (name, email, password, role, team, joining_date)
VALUES ('HR Admin', 'hr@company.com', 'password123', 'HR', 'HR', '2025-01-01'),
       ('Rahul Sharma', 'rahul@company.com', 'password123', 'MANAGER', 'Development', '2024-01-01'),
       ('Priya Singh', 'priya@company.com', 'password123', 'MANAGER', 'Testing', '2024-01-01');
INSERT INTO users (name, email, password, role, team, manager_id, joining_date)
SELECT v.name, v.email, 'password123', 'EMPLOYEE', v.team, m.id, v.joining_date::date
FROM (VALUES ('Chinmay', 'chinmay@company.com', 'Development', 'rahul@company.com', '2026-07-01'),
             ('Aman', 'aman@company.com', 'Development', 'rahul@company.com', '2026-01-15'),
             ('Riya', 'riya@company.com', 'Testing', 'priya@company.com', '2026-03-01'))
     AS v(name, email, team, manager_email, joining_date)
JOIN users m ON m.email = v.manager_email;

INSERT INTO team_leave_rules (team, max_percentage)
VALUES ('Development', 30), ('Testing', 30), ('HR', 25)
ON CONFLICT (team) DO UPDATE SET max_percentage = EXCLUDED.max_percentage;

INSERT INTO leave_balances (user_id, leave_type, total_days, used_days, year)
SELECT u.id, v.leave_type, v.total_days, v.used_days, 2026
FROM (VALUES ('chinmay@company.com', 'CASUAL', 6::numeric, 0::numeric),
             ('chinmay@company.com', 'SICK', 6, 0),
             ('aman@company.com', 'CASUAL', 12, 2),
             ('aman@company.com', 'SICK', 12, 1),
             ('riya@company.com', 'CASUAL', 10, 1),
             ('riya@company.com', 'SICK', 10, 0)) AS v(email, leave_type, total_days, used_days)
JOIN users u ON u.email = v.email;

INSERT INTO leave_requests (user_id, leave_type, start_date, end_date, days, reason, status, manager_deadline)
SELECT u.id, 'CASUAL', '2026-10-05', '2026-10-07', 3, 'Personal work',
       'PENDING_MANAGER', NOW() + INTERVAL '48 hours'
FROM users u WHERE u.email = 'chinmay@company.com';

DROP TABLE legacy_leave_audit_events;
DROP TABLE legacy_leave_requests;
DROP TABLE employees;
DROP TABLE teams;
